# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrepHero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrepHero
  pod 'GoogleMaps', '7.4.0'

end
